import { Button, TextField } from "@mui/material";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import Header from "../../components/Header/Header";
import { db } from "../../Firebase/firebase";
import Link from "@mui/material/Link";
import Typography from "@mui/material/Typography";

const Dish = () => {
  const [title, setTitle] = useState("");
  const [image, setImage] = useState("");
  const [price, setPrice] = useState();
  const [category, setCategory] = useState("");
  const router = useRouter();

  const handleAddNewDish = async (e) => {
    await addDoc(collection(db, "dishes"), {
      title: title,
      image: image,
      category: category,
      amount: 1,
      rating: "5/5",
      price: Math.floor(parseInt(price)),
      timestamp: serverTimestamp(),
    });
    router.push("/dashboard");
    setCategory("");
    setTitle("");
    setImage("");
    setPrice("");
  };

  function Copyright() {
    return (
      <Typography variant="body2" color="text.secondary" align="center">
        {"Copyright © "}
        <Link color="inherit" href="https://mui.com/">
          Hungerz Restaurant
        </Link>{" "}
        {new Date().getFullYear()}
        {"."}
      </Typography>
    );
  }

  return (
    <div className="h-screen flex flex-col">
      <Head>
        <title>Add new dish: Hungerz Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="h-full p-2 flex flex-col justify-center items-center ">
        <h1 className="text-lg font-bold md:text-2xl">Add a new dish!</h1>
        <form className="flex flex-col w-[90%] p-2 h-full md:w-[70%]">
          <TextField
            label="Category"
            placeholder="Enter category"
            variant="outlined"
            className="m-3"
            required
            value={category}
            onChange={(e) => setCategory(e.target.value)}
          />

          <TextField
            id="outlined-basic"
            label="Dish Title"
            variant="outlined"
            className="m-3"
            required
            value={title}
            onChange={(e) => setTitle(e.target.value)}
          />
          <TextField
            label="Image"
            placeholder="Enter image url"
            variant="outlined"
            className="m-3"
            required
            value={image}
            onChange={(e) => setImage(e.target.value)}
          />

          <TextField
            id="outlined-basic"
            type="number"
            label="Price"
            placeholder="Enter amount of the Dish"
            variant="outlined"
            className="m-3"
            required
            value={price}
            onChange={(e) => setPrice(e.target.value)}
          />
          <Button
            disabled={!title || !category || !image || !price}
            onClick={handleAddNewDish}
            variant="outlined"
            className="m-3"
          >
            Add
          </Button>
        </form>

        <Copyright />
      </div>
    </div>
  );
};

export default Dish;
