import Head from "next/head";
import { useState } from "react";
import Header from "../../components/Header/Header";

const Dish = () => {
  const [title, setTitle] = useState("");
  const [image, setImage] = useState("");
  const [price, setPrice] = useState(0);
  const [amount, setAmount] = useState(1);

  const handleAddNewDish = (e) => {
    console.log("Added new dish");
  };

  return (
    <div className="h-screen flex flex-col">
      <Head>
        <title>Add new dish: Hungerz Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="h-full p-2 flex flex-col justify-center items-center ">
        <input
          className="m-4 p-2"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          placeholder="Enter title"
        />

        <input
          className="m-4 p-2"
          value={image}
          onChange={(e) => setImage(e.target.value)}
          placeholder="Enter image"
        />

        <input
          className="m-4 p-2"
          type="number"
          value={price}
          onChange={(e) => setPrice(e.target.value)}
          placeholder="Enter price"
        />

        <button onClick={handleAddNewDish}>Add new dish</button>
      </div>
    </div>
  );
};

export default Dish;
