import Head from "next/head";
import CheckoutForm from "../../components/CheckoutComponents/CheckoutForm";

const Checkout = () => {
  return (
    <div className="h-screen flex flex-col ">
      <Head>
        <title>Checkout: Hungerz Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CheckoutForm />
    </div>
  );
};

export default Checkout;
