import Head from "next/head";
import React, { useEffect, useState } from "react";
import Header from "../../components/Header/Header";
import { signOut } from "firebase/auth";
import { useRouter } from "next/router";
import { useStateValue } from "../../context-api/StateProvider";
import OrderCard from "../../components/OrderCard/OrderCard";
import { onSnapshot, orderBy, collection } from "firebase/firestore";
import { onAuthStateChanged } from "firebase/auth";
import { db, auth } from "../../Firebase/firebase";
import Box from "@mui/material/Box";
import Fab from "@mui/material/Fab";
import AddIcon from "@mui/icons-material/Add";
import ArrowRightAltIcon from "@mui/icons-material/ArrowRightAlt";

const Dashboard = () => {
  const [{ user }, dispatch] = useStateValue();
  const [cartItems, setCartItems] = useState([]);
  const router = useRouter();

  // An oberver to check user sign-in state when app loads
  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (authChef) => {
      if (authChef) {
        dispatch({
          type: "SET_USER",
          user: authChef,
        });
      } else {
        router.push("/chef");
      }
    });
    // clean up action
    return () => {
      unsubscribe();
    };
  }, [dispatch, router]);

  // fetch all the items from orders collection
  useEffect(() => {
    const unsubscribe = onSnapshot(
      collection(db, "orders"),
      orderBy("timestamp", "desc"),
      (snapshot) => setCartItems(snapshot.docs)
    );
    return unsubscribe;
  }, []);

  // function to logout user
  const handleSignOut = () => {
    signOut(auth)
      .then(() => {
        dispatch({
          type: "SET_USER",
          user: null,
        });
        router.push("/login");
        console.log("User signed out successfully");
      })
      .catch((err) => console.log(err));
  };
  return (
    <div className="h-screen flex flex-col">
      <Head>
        <title>Cooking orders: Hungerz Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="h-full p-2">
        <div className=" p-2 flex flex-col md:flex-row md:justify-between md:items-center px-4">
          <h1 className="text-lg text-gray-800 md:text-xl font-semibold">
            Chef {user?.displayName}, start cooking!
          </h1>

          <p
            onClick={() => router.push("/available")}
            className="w-max bg-blue-500 text-white text-sm font-semibold p-2 rounded-md cursor-pointer"
          >
            Check Available Dishes <ArrowRightAltIcon />{" "}
          </p>
        </div>
        <div className="p-2">
          <div className="flex flex-col m-2 items-center sm:grid md:grid-cols-2 xl:grid-cols-3 3xl:flex flex-wrap justify-center">
            {cartItems.map((item) => (
              <OrderCard
                key={item.id}
                id={item.id}
                username={item.data().username}
                email={item.data().email}
                profileImg={item.data().profileImg}
                status={item.data().status}
                totalPay={item.data().totalPay}
                feedback={item.data().feedback}
                timestamp={item.data().timestamp}
                items={item.data().items}
              />
            ))}
          </div>
        </div>
      </div>
      <Box
        className="fixed right-0 bottom-1 z-50"
        sx={{ "& > :not(style)": { m: 1 } }}
      >
        <Fab
          onClick={() => router.push("/dish")}
          className="bg-blue-500 hover:bg-blue-500"
          aria-label="add"
        >
          <AddIcon className="text-white" />
        </Fab>
      </Box>
    </div>
  );
};

export default Dashboard;
